#!/usr/bin/env bash
cd $HOME/GLOBLA
install() {
rm -rf $HOME/.telegram-cli
sudo apt-get update
sudo apt-get upgrade
sudo timedatectl set-timezone Asia/Baghdad
sudo apt-get install screen
sudo apt-get install libreadline-dev libconfig-dev libssl-dev lua5.2 liblua5.2-dev lua-socket lua-sec lua-expat libevent-dev make unzip redis-server autoconf g++ libjansson-dev libpython-dev expat libexpat1-dev
sudo apt-get update
sudo apt-get install upstart-sysv
wget http://luarocks.org/releases/luarocks-2.2.2.tar.gz;tar zxpf luarocks-2.2.2.tar.gz;cd luarocks-2.2.2 && ./configure
sudo make bootstrap
sudo luarocks install luasocket
sudo luarocks install luasec
sudo apt-get install libconfig++9v5 -y 
sudo apt-get install libstdc++6 -y
sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y 
sudo apt-get install lua-lgi -y  
sudo apt-get install libnotify-dev -y 
sudo chmod +x tg
lua GLOBLA.lua
sudo chmod +x GLOBLA
sudo chmod +x RUN
./RUN
}
if [ "$1" = "install" ]; then
install
else
if [ ! -f ./tg ]; then
echo "Tg Is Not Found"
exit 1
fi
sudo chmod +x tg
lua GLOBLA.lua
sudo chmod +x GLOBLA
sudo chmod +x RUN
./RUN
fi
