#!/usr/bin/env bash
cd $HOME/GLOBLA
offices() {
Version=`lsb_release -rs | cut -f1 -d"."`
sudo apt-get update -y
sudo apt-get upgrade -y 
sudo timedatectl set-timezone Asia/Baghdad
sudo apt-get install screen -y
sudo apt-get install libreadline-dev libconfig-dev libssl-dev lua5.2 liblua5.2-dev lua-socket lua-sec lua-expat libevent-dev make unzip redis-server autoconf g++ libjansson-dev libpython-dev expat libexpat1-dev -y
sudo apt-get update -y 
sudo apt-get install upstart-sysv -y
wget http://luarocks.org/releases/luarocks-2.2.2.tar.gz;tar zxpf luarocks-2.2.2.tar.gz;cd luarocks-2.2.2 && ./configure -y
sudo make bootstrap -y
sudo luarocks install luasocket -y
sudo luarocks install luasec -y
sudo apt-get install libconfig++9v5 -y 
sudo apt-get install libstdc++6 -y
sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y 
sudo apt-get install lua-lgi -y  
sudo apt-get install libnotify-dev -y
if [ "$Version" == "18" ]; then
echo -e "\033[0;31m\n~ Installing Depedencies For Ubuntu 18... \n\033[0m"
cd /lib/x86_64-linux-gnu/ && sudo ln -s libreadline.so.7.0 libreadline.so.6
wget "ibotcorp.com/files/compat-libevent2-5_2.0.21-1ubuntu18_amd64.deb" && sudo dpkg -i compat-libevent2-5_2.0.21-1ubuntu18_amd64.deb
rm compat-libevent2-5_2.0.21-1ubuntu18_amd64.deb
sudo chmod +x tg
lua GLOBLA.lua
sudo chmod +x GLOBLA
sudo chmod +x RUN
./RUN
}
if [ "$1" = "offices" ]; then
offices
else
if [ ! -f ./tg ]; then
echo "Tg Is Not Found"
exit 1
fi
sudo chmod +x tg
lua GLOBLA.lua
sudo chmod +x GLOBLA
sudo chmod +x RUN
./RUN
fi
fi
